quarkus:
    datasource:
        db-kind: postgresql
        username: postgres
        password: password
        devservices:
            enabled: true
            port: 50615

#    datasource:
#        db-kind: h2
#        jdbc.url: jdbc:h2:mem:testdb
#        jdbc.driver: org.h2.Driver
#        username: admin
    log:
        level: INFO
    hibernate-orm:
        database:
            generation: drop-and-create
    http:
        access-log:
            enabled: true
